# Generated by Django 3.1.1 on 2020-09-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200929_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(default='76f418b1-0817-48a1-b00e-8456ce205b94', max_length=32, primary_key=True, serialize=False),
        ),
    ]
