# Generated by Django 3.1.1 on 2020-09-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200929_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(default='84059e6b-8239-432c-9962-c8648f9e6282', max_length=64, primary_key=True, serialize=False),
        ),
    ]
